version: 2

project_name: motf

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: motf
    main: ./cmd/motf
    binary: motf
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/TechnicallyJoe/terraform-motf/internal/cli.version={{.Version}}
      - -X github.com/TechnicallyJoe/terraform-motf/internal/cli.commit={{.Commit}}
      - -X github.com/TechnicallyJoe/terraform-motf/internal/cli.date={{.Date}}

archives:
  - id: default
    formats: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    include:
      - '^feat(\(.+\))?!?:'
      - '^fix(\(.+\))?!?:'
      - '^chore(\(.+\))?!?:'
      - '^refactor(\(.+\))?!?:'
      - 'BREAKING CHANGE:'
    exclude:
      - '^chore\(wiki-sync\):'
      - Merge pull request
      - Merge branch

  groups:
    - title: "⚠️ Breaking Changes"
      regexp: '^.*!:|BREAKING CHANGE:'
      order: 0
    - title: "🚀 Features"
      regexp: '^feat(\(.+\))?!?:'
      order: 1
    - title: "🐛 Bug Fixes"
      regexp: '^fix(\(.+\))?!?:'
      order: 2
    - title: "♻️ Refactoring"
      regexp: '^refactor(\(.+\))?!?:'
      order: 3
    - title: "🔧 Maintenance"
      regexp: '^chore(\(.+\))?!?:'
      order: 4

release:
  github:
    owner: TechnicallyJoe
    name: terraform-motf
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## motf v{{ .Version }}

    To install, download the appropriate binary for your platform below.
  footer: |
    **Full Changelog**: https://github.com/TechnicallyJoe/terraform-motf/compare/{{ .PreviousTag }}...{{ .Tag }}
