version: 2

project_name: motf

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: motf
    main: .
    binary: motf
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/TechnicallyJoe/terraform-motf/cmd.version={{.Version}}
      - -X github.com/TechnicallyJoe/terraform-motf/cmd.commit={{.Commit}}
      - -X github.com/TechnicallyJoe/terraform-motf/cmd.date={{.Date}}

archives:
  - id: default
    formats: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
  groups:
    - title: "🚀 Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "🔧 Other"
      order: 999

release:
  github:
    owner: TechnicallyJoe
    name: terraform-motf
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## motf {{ .Version }}

    To install, download the appropriate binary for your platform below.
  footer: |
    **Full Changelog**: https://github.com/TechnicallyJoe/terraform-motf/compare/{{ .PreviousTag }}...{{ .Tag }}
