# motf Demo Configuration
# Root is set to current directory (where .motf.yml is found)
root: .
binary: terraform

# Test configuration
test:
  engine: "terratest"  # Options: terratest, terraform, tofu
  args: ""             # Additional arguments passed to the test command

# Custom tasks
tasks:
  hello-world:
    description: "Writes hello world to the console"
    shell: sh
    command: |
      echo "Hello"
      echo "World"

  list-files:
    description: "List files in the module directory"
    command: "ls -la"

  show-path:
    description: "Show current working directory"
    shell: bash
    command: "pwd && echo 'Module: '$(basename $(pwd))"
